### ISSUE TITLE
Install success, but no package

### ISSUE THREAD

**Issue by Erhannis** [codestation/vitamtp#10]
I've run

```
./autogen.sh
./configure
make
sudo make install
```
successfully, but when I try to install the qcma deb (https://codestation.github.io/qcma/ , with `dpkg -i qcma_0.4.2_amd64.deb`), it tells me:

```
 qcma depends on libvitamtp5 (>= 2.5.5); however:
  Package libvitamtp5 is not installed.
```

I don't really understand the structure of configuration that controls how/whether something is installed to what package, but the file `debian/control` contains `Package: libvitamtp5`, so I'd have expected it to install.  `apt list --installed` doesn't show any packages with the word "vita" in them.  Any idea what's up?

I'm on Debian 9.8, 64 bit machine.

**Comment by codestation** [comment]
Do not mix manual and package installations. Also i don't know why it doesn't list the vitamtp deb files.

You can either download it from here: https://download.opensuse.org/repositories/home:/codestation/Debian_9.0/amd64/

Or follow the instuctions to use the repository instead, so it will install vitamtp automatically when installing qcma.

```
wget -nv https://download.opensuse.org/repositories/home:codestation/Debian_9.0/Release.key -O Release.key
apt-key add - < Release.key
apt-get update
```

```
echo 'deb http://download.opensuse.org/repositories/home:/codestation/Debian_9.0/ /' > /etc/apt/sources.list.d/home:codestation.list
apt-get update
apt-get install qcma
```

**Comment by Erhannis** [comment]
Yeah, I think I eventually downloaded the vitamtp package from a repo and installed it with dpkg.  Thanks.
